### ISSUE TITLE
Directory for people's public keys

### ISSUE THREAD

**Issue by dongcarl** [bitcoin-core/guix.sigs#133]
We should have a directory where it's just people's public keys to avoid over-reliance on keyservers and this situation: https://github.com/bitcoin-core/bitcoincore.org/issues/793#issuecomment-920543806

We can check via CI that everyone who uploads has a key and that signatures are valid.

**Comment by MarcoFalke** [comment]
> We can check via CI that everyone who uploads has a key and that signatures are valid.

So whenever a key expires, or is revoked, or otherwise gets stale, it will result in a red CI?


By including a directory here, you are basically (manually) running a keyserver. This will likely require scripts to maintain the keyserver directory in this repo.

**Comment by gruve-p** [comment]
Maybe this directory can be used: https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys

**Comment by laanwj** [comment]
I'm not sure. I've floated similar ideas before after being frustrated at the keyservers once again. But it seems like a lot of maintenance overhead. But if you're willing to maintain this, why not.

> By including a directory here, you are basically (manually) running a keyserver. This will likely require scripts to maintain the keyserver directory in this repo.

Good point. You could automate it by periodically fetching the keys in `builder-keys` from the keyserver, or running `refresh-keys`. Which makes you essentially a keyserver.

> Maybe this directory can be used: https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys

If we do it it should be a separate repo, not clutter the main one.

**Comment by hebasto** [comment]
If we could assume that users use the same keys to sign guix builds as they use to sign commits, we could count on personal keys like https://github.com/hebasto.gpg

**Comment by bullsandbears** [comment]
Es währ von Vorteil wenn alle Schlüssel nach Benutzungs Datum Zeit sortiert währen damit währe es sehr übersichtlich Dokumentiert.
Es bräuchte ein kleines Protokoll das bei benutzen des Schlüssels den Schlüssel der liste hinzufügt mit Zeit und Datum 
Und die Geänderten Dateien als link

**Comment by MarcoFalke** [comment]
I guess this can be done by having the CI check the key and attestation in every pull request, but only for the keys/attestations changed in the pull request?

**Comment by MarcoFalke** [comment]
Fixed in https://github.com/bitcoin-core/guix.sigs/pull/535
